this = {
  events: [
    {
      event: {
        banner: { headline: "", subtitle: "", emoji: "" },
        category: "cfb",
        center_court: { x: 156, y: 117, width: 8, height: 8 },
        datetime_local: "2021-09-18T03:30:00",
        datetime_utc: "2021-09-18T08:30:00",
        id: "60122c475bee090001978edc",
        map_url:
          "https://maps.gametime.co/v2/tiger_stadium/collegefootball/collegefootball-8.png",
        min_price: { total: 0, prefee: 0 },
        name: "Central Michigan Chippewas at LSU Tigers",
        performers: [
          { id: "55c3ab5ff80c412103000003", primary: true },
          { id: "5a73932625f2c553edf4ff30", primary: false },
        ],
        sales_cut_off: "2021-09-18T08:45:00Z",
        section_map_id: "5d5c171af145531a354e9c61",
        tbd: false,
        time_tbd: true,
        date_tbd: false,
        venue_id: "55c3ab43f80c412103000001",
        venue_config: "collegefootball",
      },
      performers: [
        {
          abbrev: "LSU",
          category: "cfb",
          category_group: "sport",
          contrast_color: "FDD023FF",
          display_type: "performer_vs_performer",
          id: "55c3ab5ff80c412103000003",
          hero_image_url: "https://images.gametime.co/cfblsu/hero@4x.jpg",
          medium_name: "LSU Tigers",
          name: "LSU Football",
          primary_color: "652DAEFF",
          short_name: "Tigers",
          slug: "cfblsu",
          meta: { score_boost: null },
        },
        {
          abbrev: "CMU",
          category: "cfb",
          category_group: "sport",
          contrast_color: "",
          display_type: "performer_vs_performer",
          id: "5a73932625f2c553edf4ff30",
          hero_image_url: "https://images.gametime.co/cfbcmu/hero@4x.jpg",
          medium_name: "CMU Chippewas",
          name: "Central Michigan Football",
          primary_color: "04529CFF",
          short_name: "Chippewas",
          slug: "cfbcmu",
          meta: { score_boost: null },
        },
      ],
      venue: {
        city: "Baton Rouge",
        id: "55c3ab43f80c412103000001",
        location: { lat: 30.412, lon: -91.1838 },
        name: "LSU Tiger Stadium",
        show_currency: false,
        slug: "tiger_stadium",
        state: "LA",
        timezone: "America/Chicago",
        metro: "neworleans",
        image_url:
          "https://maps.gametime.co/v2/tiger_stadium/cfb_lsu/cfb_lsu-8.png",
        meta: { score_boost: null },
      },
      meta: {
        search_score: 21.099005,
        sort_order: 14,
        display_group: "top_pick",
        popularity_score: 0,
        score_boost: 0,
      },
    },
    {
      event: {
        banner: { headline: "", subtitle: "", emoji: "" },
        category: "nascar",
        center_court: { x: 133, y: 119, width: 11, height: 9 },
        datetime_local: "2021-08-22T15:00:00",
        datetime_utc: "2021-08-22T19:00:00",
        id: "5f76469788e56d000107c3f9",
        map_url:
          "https://maps.gametime.co/v2/michigan_intl_speedway/nascar/nascar-8.png",
        min_price: { total: 0, prefee: 0 },
        name: "NASCAR Cup Series Race at Michigan",
        performers: [
          { id: "5e41c8bc48bdd7003a137e19", primary: true },
          { id: "5e41c8bc48bdd7003a137e19", primary: false },
        ],
        sales_cut_off: "2021-08-22T20:30:00Z",
        section_map_id: "5cf0187c983f08da16c25dc7",
        tbd: false,
        time_tbd: false,
        date_tbd: false,
        venue_id: "5ceffbaf99c23b001a396cbc",
        venue_config: "nascar",
      },
      performers: [
        {
          abbrev: "NASCAR",
          category: "nascar",
          category_group: "sport",
          contrast_color: "",
          display_type: "performer_at_venue",
          id: "5e41c8bc48bdd7003a137e19",
          hero_image_url:
            "https://images.gametime.co/nascarnascarcupserieschampionship/hero@4x.jpg",
          medium_name: "NASCAR Cup Series",
          name: "NASCAR Cup Series",
          primary_color: "7ed321FF",
          short_name: "NASCAR Cup Series",
          slug: "nascarnascarcupserieschampionship",
          meta: { score_boost: null },
        },
        {
          abbrev: "NASCAR",
          category: "nascar",
          category_group: "sport",
          contrast_color: "",
          display_type: "performer_at_venue",
          id: "5e41c8bc48bdd7003a137e19",
          hero_image_url:
            "https://images.gametime.co/nascarnascarcupserieschampionship/hero@4x.jpg",
          medium_name: "NASCAR Cup Series",
          name: "NASCAR Cup Series",
          primary_color: "7ed321FF",
          short_name: "NASCAR Cup Series",
          slug: "nascarnascarcupserieschampionship",
          meta: { score_boost: null },
        },
      ],
      venue: {
        city: "Brooklyn",
        id: "5ceffbaf99c23b001a396cbc",
        location: { lat: 42.0628, lon: -84.2414 },
        name: "Michigan International Speedway",
        show_currency: false,
        slug: "michigan_intl_speedway",
        state: "MI",
        timezone: "America/New_York",
        metro: "detroit",
        image_url:
          "https://www.mispeedway.com/~/media/CC5F0AD69F054E66A48A22A154A2D936.ashx",
        meta: { score_boost: null },
      },
      meta: {
        search_score: 21.099005,
        sort_order: 15,
        display_group: "events",
        popularity_score: 0,
        score_boost: 0,
      },
    },
  ],
  performers: [
    {
      abbrev: "MICH",
      category: "cbb",
      category_group: "sport",
      contrast_color: "FFCB05FF",
      display_type: "performer_vs_performer",
      id: "54d2d35764f9621ef0000008",
      hero_image_url: "https://images.gametime.co/cbbmich/hero@4x.jpg",
      medium_name: "MICH Wolverines",
      name: "Michigan Basketball",
      primary_color: "00376BFF",
      short_name: "Wolverines",
      slug: "cbbmich",
      meta: {
        search_score: 24.516455,
        sort_order: 0,
        display_group: "performers",
        popularity_score: 0,
        score_boost: 0,
      },
    },
    {
      abbrev: "MICH",
      category: "cbs",
      category_group: "sport",
      contrast_color: "",
      display_type: "performer_vs_performer",
      id: "5c369003c27a15001703204d",
      hero_image_url: "https://images.gametime.co/cbsmich/hero@4x.jpg",
      medium_name: "MICH Wolverines",
      name: "Michigan Baseball",
      primary_color: "4a90e2FF",
      short_name: "Wolverines",
      slug: "cbsmich",
      meta: {
        search_score: 24.516455,
        sort_order: 1,
        display_group: "performers",
        popularity_score: 0,
        score_boost: 0,
      },
    },
  ],
  venues: [
    {
      city: "Ann Arbor",
      id: "598387bd9da0d48c0d7eb8b6",
      location: { lat: 42.2795, lon: -83.7418 },
      name: "Michigan Theater",
      show_currency: false,
      slug: "michigan_theater",
      state: "MI",
      timezone: "America/Chicago",
      metro: "detroit",
      image_url:
        "https://maps.gametime.co/v2/michigan_theater/music/music-8.png",
      meta: {
        search_score: 22.750715,
        sort_order: 7,
        display_group: "venues",
        popularity_score: 0,
        score_boost: 0,
      },
    },
    {
      city: "Ann Arbor",
      id: "541a27703bf3767221000005",
      location: { lat: 42.2657, lon: -83.7495 },
      name: "Michigan Stadium",
      show_currency: false,
      slug: "michigan_stadium",
      state: "MI",
      timezone: "America/New_York",
      metro: "detroit",
      image_url:
        "https://maps.gametime.co/v2/michigan_stadium/cfb_mich/cfb_mich-8.png",
      meta: {
        search_score: 22.750715,
        sort_order: 8,
        display_group: "venues",
        popularity_score: 0,
        score_boost: 0,
      },
    },
  ],
  display_groups: [
    { display_name: "Top Result", slug: "top_pick", sort_order: 0 },
    { display_name: "Performers", slug: "performers", sort_order: 1 },
    { display_name: "Venues", slug: "venues", sort_order: 2 },
    { display_name: "Events", slug: "events", sort_order: 3 },
  ],
};
